### ISSUE TITLE
能否考虑更新兼容下2018版？

### ISSUE THREAD

**Issue by CNMan** [lifenjoiner/wmwb_dat2csv#1]
[wmwb18.zip](https://github.com/lifenjoiner/wmwb_dat2csv/files/3895595/wmwb18.zip)

**Comment by lifenjoiner** [comment]
已更新。
其实没必要追新：
v2018 `功能创新：简繁同台，插打拼音`，做了简繁并重，增加了繁体词库；
始终都是`国标（GB-18030）大字符集27,533个汉字`。

**Comment by CNMan** [comment]
@lifenjoiner 多谢！主要是想看看编码修正、更新情况
现在输出的csv是ANSI编码，GBK以外的字符显示问号。能不能编译linux下的bin？输出utf-8编码是不是可以解决这个问题？

**Comment by lifenjoiner** [comment]
我没有使用 Windows 以外的系统，你自己编译吧，代码只用了一些基本函数，应该没问题的
似乎你已经拿到了结果，要用 GB-18030 编码打开，是原样输出，转码工作这里就不做了
